[2024-06-01T04:21:32.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T04:21:32.214+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: soc_domain_analysis.compare_domain_urls manual__2024-06-01T04:21:32.006662+00:00 [queued]>
[2024-06-01T04:21:32.218+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: soc_domain_analysis.compare_domain_urls manual__2024-06-01T04:21:32.006662+00:00 [queued]>
[2024-06-01T04:21:32.218+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-01T04:21:32.224+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): compare_domain_urls> on 2024-06-01 04:21:32.006662+00:00
[2024-06-01T04:21:32.227+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=448) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T04:21:32.227+0000] {standard_task_runner.py:63} INFO - Started process 449 to run task
[2024-06-01T04:21:32.227+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'soc_domain_analysis', 'compare_domain_urls', 'manual__2024-06-01T04:21:32.006662+00:00', '--job-id', '3713', '--raw', '--subdir', 'DAGS_FOLDER/soc_dag.py', '--cfg-path', '/tmp/tmp6_o0ggbt']
[2024-06-01T04:21:32.228+0000] {standard_task_runner.py:91} INFO - Job 3713: Subtask compare_domain_urls
[2024-06-01T04:21:32.236+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T04:21:32.253+0000] {task_command.py:426} INFO - Running <TaskInstance: soc_domain_analysis.compare_domain_urls manual__2024-06-01T04:21:32.006662+00:00 [running]> on host f74c39de7cd3
[2024-06-01T04:21:32.289+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='soc_domain_analysis' AIRFLOW_CTX_TASK_ID='compare_domain_urls' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T04:21:32.006662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T04:21:32.006662+00:00'
[2024-06-01T04:21:32.290+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T04:21:32.294+0000] {soc_dag.py:23} INFO - Starting to compare domains
[2024-06-01T04:21:33.912+0000] {soc_dag.py:30} ERROR - Error comparing domains: name 'domain_creation_date_old' is not defined
[2024-06-01T04:21:33.913+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T04:21:33.915+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/soc_dag.py", line 24, in compare_domain_urls
    result = DomainAnalysisOperator.compare_urls("old-domain.com", "new-domain.com")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/operators/analysis.py", line 267, in compare_urls
    domain_info_old.update(domain_creation_date_old)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'domain_creation_date_old' is not defined
[2024-06-01T04:21:33.940+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=soc_domain_analysis, task_id=compare_domain_urls, run_id=manual__2024-06-01T04:21:32.006662+00:00, execution_date=20240601T042132, start_date=20240601T042132, end_date=20240601T042133
[2024-06-01T04:21:33.948+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3713 for task compare_domain_urls (name 'domain_creation_date_old' is not defined; 449)
[2024-06-01T04:21:33.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T04:21:34.004+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T04:21:34.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
